// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateText('https', { text: 'https://' });
    CreateText('tok', { text: 'Token' });
    CreateGlassButton('startbutton', { onclick: 'clickedStartStop', text: 'Start' });
    CreateGlassButton('stopbutton', { onclick: 'clickedStartStop', text: 'Stop' });
    CreateGlassButton('submithours', { onclick: 'submitHours', text: 'Submit Hours' });
    CreateText('not', { text: 'Notes' });
    CreateText('statusmsg', { text: 'statusmsg' });
    CreateText('versionInfo', { text: 'TIME TRACKER v 1.0.4' });
    CreateGlassButton('done', { onclick: 'loadProjects', text: 'Done' });
    CreateText('freshbookscom', { text: '.freshbooks.com' });
    CreateText('count', { text: '0:00:00' });
    CreateText('submitStatus', { text: 'submitStatus' });
    CreateText('url', { text: 'yoursite.freshbooks.com' });
    CreateText('needhelp', { text: 'Need Help? Find your token!' });
}
window.addEventListener('load', setupParts, false);
